// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwDCiwallJQCFQBKJz5elCI_MLiFDNyl0',
    appId: '1:902432057495:web:39c3e8ef272fb434f8e1d2',
    messagingSenderId: '902432057495',
    projectId: 'flutter-nf',
    authDomain: 'flutter-nf.firebaseapp.com',
    storageBucket: 'flutter-nf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_PUbMbPZlUGbwxetQ18PE43PplFzxL6g',
    appId: '1:902432057495:android:817f50bd369d0f8bf8e1d2',
    messagingSenderId: '902432057495',
    projectId: 'flutter-nf',
    storageBucket: 'flutter-nf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwz7F8WVLXAKJJA5R8AVTWsBVDKt2de3M',
    appId: '1:902432057495:ios:caf9e58cb2009628f8e1d2',
    messagingSenderId: '902432057495',
    projectId: 'flutter-nf',
    storageBucket: 'flutter-nf.appspot.com',
    iosClientId: '902432057495-pi9f97b9gttdv1bnf5crq73pd6qfv1ml.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEx',
  );
}
